<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>
---
title: "ETC 1010 Assignment 1"

---


```{r, fig.width=21,fig.height=5}
library(readxl)
passengers <- read_xls("data/WebAirport_FY_1986-2017.xls", sheet=3, skip=6)
library(tidyverse)
passengers <- passengers %>% gather(INBOUND,OUTBOUND,INBOUND__1,OUTBOUND__1,key="bound",value="count")
passengers1 <- passengers %>% select(AIRPORT,Year,bound,count)
passengers1 <- passengers1 %>% filter(AIRPORT!="TOTAL AUSTRALIA")

dori <- function(x){
  if (x=="INBOUND"|x=="OUTBOUND") {
    y <- "DOMESTIC"
  } else {
    y <- "INTERNATIONAL"
  }
  return(y)
}

del1 <- function(x){
  y  <- substr(x,1,3)
  if (y == "INB") {y <- "IN"}
  return(y)
}


passengers1 <- na.omit(passengers1)
passengers1 <- passengers1 %>% mutate(type='010')
n <- nrow(passengers1)
for (i in 1:n) {
  passengers1[i,5] <- dori(passengers1[i,3])
  passengers1[i,3] <- del1(passengers1[i,3])
  
}

passengers2 <- passengers1
passengers2 <- mutate(passengers2,type1=substr(type,1,1))
ggplot(passengers2,aes(type1,fill=type)) + 
  geom_bar(aes(weight=count/1000000)) + 
  facet_grid(.~Year) +
  ylab("Million of people") +
  theme(legend.position="top") +
  xlab("Type of flight")

passengers2 <- passengers1 %>% filter(type=="DOMESTIC")
passengers2 <- passengers2 %>% spread(key=bound,value=count)

ggplot(passengers2,aes(x=IN/1000000,y=OUT/1000000)) +
  geom_point() +
  facet_grid(.~Year) +
  xlab("Inbound(Million of people)") +
  ylab("Outbound(Million of people)")

passengers3 <- data.frame(filter(passengers2,Year=="2016-17"))
r <- passengers3[order(passengers3[,4],decreasing=T),1]
paste(r[1],", ",r[2],", and",r[3],"are three airports with much higher numbers.")

passengers2 <- passengers1 %>% filter(type=="INTERNATIONAL")
passengers2 <- passengers2 %>% spread(key=bound,value=count)

ggplot(passengers2,aes(x=IN/1000000,y=OUT/1000000)) +
  geom_point() +
  facet_grid(.~Year) + 
  xlab("Inbound(Million of people)") +
  ylab("Outbound(Million of people)")
```

From each of plots, we can see that:

1.For the first bar chart, we could know that more and more people choose airplane as conveyance between 1985 and 2017 in Australia. Furthermore, there were more domestic flights than international flights. In 1989-1990, the number of domestic flights decreased by around 30%, while the number of international flights remained stable. After reading some articles from the Internet, we believe that it might be caused by the 1989 Australian pilots' dispute.

2.For the second plot, from 1985 to 2017, the number of domestic inbound and outbound passenger displayed a growth. Obviously, there was a significantly positive correaltion between them.
Besides, Sydney, Melbourne and Brisbane airports had more passengers.

3.For the third plot, similarly, the number of international inbound and outbound passenger increased in 1985-2017, and there was also a positive correaltion between them.
