---
title: "Week 3 Assignment"
author: Data Lads
output: html_document
---


Question 1: Tidying the data
```{r airport}
library(tidyverse)
library(tidyr)
library(dplyr)
library(readxl)
passengers <- read_xls("data/WebAirport_FY_1986-2017.xls", sheet=3, skip=6)


#summary(passengers)

#names(passengers)
(passengers <- passengers[-c(1:32), c(2, 3, 5:13)])
passengers_plot2 <- passengers %>%
  select(-TOTAL, -TOTAL__1, -TOTAL__2, -INBOUND__2, -OUTBOUND__2) %>%
  rename(IN = INBOUND, OUT = OUTBOUND, IN = INBOUND__1, OUT = OUTBOUND__1) %>%
  gather(Domestic, Count, c(3, 4)) %>%
  gather(International, Count, c(3, 4))


passengers_plot1 <- passengers_plot2 %>%
  gather(type_of_flight, Bound, Domestic, International) %>%
  mutate(Count = as.integer(Count))

(passengersQ1 <- passengers_plot1[, c(-3)])

#passengersQ1 %>% count(type_of_flight)

```

Question 2: Bar Chart
```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(readxl)
passengers <- read_xls("data/WebAirport_FY_1986-2017.xls", sheet=3, skip=6)
passengers

#summary(passengers)

#names(passengers)
(passengers <- passengers[-c(1:32), c(2, 3, 5:13)])
passengers_plot2 <- passengers %>%
  select(-TOTAL, -TOTAL__1, -TOTAL__2, -INBOUND__2, -OUTBOUND__2) %>%
  rename(IN = INBOUND, OUT = OUTBOUND, IN = INBOUND__1, OUT = OUTBOUND__1) %>%
  gather(Domestic, Count, c(3, 4)) %>%
  gather(International, Count, c(3, 4))
  


passengers_plot1 <- passengers_plot2 %>%
  gather(type_of_flight, Bound, Domestic, International) %>%
  mutate(Count = as.integer(Count))
passengers_plot1

(passengersQ1 <- passengers_plot1[, c(-3)])

ggplot(passengers_plot1, aes(x = type_of_flight, fill = type_of_flight)) +
  geom_bar(aes(weight = Count)) + 
  scale_fill_brewer(palette = "Dark2") + 
  xlab("Type of Flight") + 
  ylab("Count") + 
  facet_grid(~ Year)
```

Question 3: Domestic Scatter Plot
```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(readxl)
passengers <- read_xls("data/WebAirport_FY_1986-2017.xls", sheet=3, skip=6)


#summary(passengers)

#names(passengers)
(passengers1 <- passengers[-c(1:32), c(2, 3, 5:13)])
passengers_plot2 <- passengers1 %>%
  select(-TOTAL, -TOTAL__1, -TOTAL__2, -INBOUND__2, -OUTBOUND__2) %>%
  rename(IN = INBOUND, OUT = OUTBOUND, IN = INBOUND__1, OUT = OUTBOUND__1) %>%
  gather(Domestic, Count, c(3, 4)) %>%
  gather(International, Count, c(3, 4))


passengers1 <- passengers1 %>%
  mutate(Year = sub("-", "", Year))


passengers1 <- passengers1 %>%
  mutate(Year = as.integer(Year))


passengers1 <- passengers1 %>%
  mutate(INBOUND = as.integer(INBOUND))


passengers1 <- passengers1 %>%
  mutate(OUTBOUND = as.integer(OUTBOUND))


ggplot(passengers1, aes(x = INBOUND, y = OUTBOUND)) + 
  geom_point() + 
  facet_grid(~ Year)
```

Question 4: International Scatter Plot
```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(readxl)
passengers <- read_xls("data/WebAirport_FY_1986-2017.xls", sheet=3, skip=6)


#summary(passengers)

#names(passengers)
(passengers1 <- passengers[-c(1:32), c(2, 3, 5:13)])
passengers_plot2 <- passengers1 %>%
  select(-TOTAL, -TOTAL__1, -TOTAL__2, -INBOUND__2, -OUTBOUND__2) %>%
  rename(IN = INBOUND, OUT = OUTBOUND, IN = INBOUND__1, OUT = OUTBOUND__1) %>%
  gather(Domestic, Count, c(3, 4)) %>%
  gather(International, Count, c(3, 4))

passengers1 <- passengers1 %>%
  mutate(Year = sub("-", "", Year))

passengers1 <- passengers1 %>%
  mutate(Year = as.integer(Year))

passengers1 <- passengers1 %>%
  mutate(INBOUND__1 = as.integer(INBOUND__1))

passengers1 <- passengers1 %>%
  mutate(OUTBOUND__1 = as.integer(OUTBOUND__1))


ggplot(passengers1, aes(x = INBOUND__1, y = OUTBOUND__1)) + 
  geom_point() + 
  #theme(aspect.ratio = 1) + 
  facet_grid(~ Year)
```

Question 5: Interpreting the Data
From each plot it is clear that the amount of people flying is increasing per year.

