---
title: "ETC 1010 Assignment 1"
author: "Di Cook"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  error = FALSE, 
  collapse = TRUE,
  comment = "",
  fig.height = 8,
  fig.width = 12,
  fig.align = "center",
  cache = FALSE
)
```

# Instructions

- This is a team assignment. You can create your own team, of between 2-4 people. 
- You need to write a report with answers to each of the questions. 
- Turn in the `html` output file, and also the `Rmd` file. 
- Create a team name, and use this on the report
- Separately you need to provide a separate page to one of the tutors that contains the team name, members of the team, and the % effort from each team member. Your grade for the assignment will be adjusted by % effort. If the effort is different from 1/n, all members need to sign off on this.
- Total points for the assignment is 20. Five points of the score from the assignment will be given by another team, who will give you full marks if they can compile your report, and get the same answers as you, and find your explanations of the plots understandable and informative.

# Exercise

- From the web site [Department of Infrastructure, Regional Development and Cities](https://bitre.gov.au/publications/ongoing/airport_traffic_data.aspx) download the Airport Traffic Data 1985–86 to 2016–17. It is 2.7Mb.
- Extract the "Airport Passengers" table into R with this code.

```
library(readxl)
passengers <- read_xls("data/WebAirport_FY_1986-2017.xls", sheet=3, skip=6)
```

- Tidy the data, to produce a data set with these columns
    - airport: all of the airports. (You can remove the TOTAL, because this can be easily recalculated as needed.)
    - year 
    - type_of_flight: DOMESTIC, INTERNATIONAL
    - bound: IN or OUT

- Use your data to make 
    - a barchart of type of flight facetted by year.
    - a scatterplot of domestic inbound vs outbound passengers facetted by year. There are three airports with much higher numbers, which are these three?
    - a scatterplot of international inbound vs outbound passengers facetted by year

- Write a paragraph explaining what you learn from each of the plots

