---
title: "ETC 1010 Assignment 2"
author: "Professor Di Cook, EBS, Monash U."
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  error = FALSE, 
  collapse = TRUE,
  comment = "",
  fig.height = 8,
  fig.width = 12,
  fig.align = "center",
  cache = FALSE
)
```

# Instructions

- This is a team assignment. 
- You need to write a report with answers to each of the questions. 
- Turn in the `html` output file, and also the `Rmd` file. 
- Total points for the assignment is 20. Five points of the score from the assignment will be given by another team, who will give you full marks if they can compile your report, and get the same answers as you, and find your explanations of the plots understandable and informative. Five points will be for individual effort. And the remaining 10 points will be the final group report.

# Exercise

Smart meters are now installed at every property in Melbourne. The Victorian government has a current initiative to encourage households to examine their energy use and particularly to get a better deal on energy pricing. Their tool to compare suppliers is at https://compare.energy.vic.gov.au. If you use this tool between now and the end of the year, you will get an energy rebate of $50.

Your task is to get the electricity usage data for your household. It is relatively straightforward. You need to go to your provider's page, which can be determined by visiting https://www.energy.vic.gov.au/electricity/electricity-distributors. If you have a recent bill, your meter number will be on it. You need this to create a login, so that you can download your data. 

The format of the data should `csv` and look something like mine, which is provided, `meter1.csv`. In addition, there should be a web page, [like this one from citipower](https://customermeterdata.portal.powercor.com.au/customermeterdata/articles/Question/A12-How-do-I-read-the-detailed-report?retURL=%2Fcustomermeterdata%2Fapex%2FCADArticleList&popup=true) describing the format of the data, that will be useful when you are trying to tidy it. You should be able to see half hourly electricity usage. 

You only need one data set per group. Everyone in the group should work on this one. If you have problems getting your own data, we will provide you with some. 

1. Describe the steps that you will need to take to read in your electricity usage, and tidy it. 

2. Tidy your data, using the `tidyverse` functions. The end product should look something like this:

```
  date       halfhour   kwh
  <date>        <dbl> <dbl>
1 2017-11-24      0.5     0
2 2017-11-24      0.5     0
3 2017-11-24      1       0
4 2017-11-24      1       0
5 2017-11-24      1.5     0
6 2017-11-24      1.5     0
```

although your `halfhour` variable might be more explicit like 12:00-12:30, 12:30-01:00, 01:00-01:30, ... And you might want to add week day, month, year variables. 

3. Make a line plot of half-hourly usage for these two days, Sunday August 5, 2018 and Wednesday Aug 8, 2018. Describe what you learn about electricity use on these two days. 

4. Aggregate your daily kwh usage. Make a side-by-side boxplot of usage by week day. Are there some days of the week that you use more electricity than others?

5. Decide on several (about 3) more types of plots to make to learn about your energy usage. Make these plots and write some paragraphs describing what you have learned. 

# Grading

Points for the assignment will be based on:

- How well you have explained your tidying procedures.
- Whether the Rmd file, can take your data file as provided,  produce the tidy data, and plots reported in your final submission.
- Accuracy of your answers to the given questions. 
- Creativeness in exploring your energy use, and plots used to tell a story. 
